sudo: false  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/  
language: java
jdk:
  - openjdk11
env:
  - DSPLAY=:0

before_install:
  - cd registrar; pwd 

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

env:
  global:
#  - TERM=dumb
#  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"

# after_failure: ./backend/travis-failure.sh
