sudo: false  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/  
language: groovy  
jdk:
  - openjdk11
env:
  - DSPLAY=:0

before_install:
  - cd registrar; pwd 

before_script:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

test:
  post:
  - cd registrar; if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi

env:
  global:
#  - TERM=dumb
#  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"

# after_failure: ./backend/travis-failure.sh
